name: ğŸš€ Production deployment
# Only trigger, when the build workflow succeeded
on:
  push:
    branches: [ "main" ]

env:
  AWS_REGION: eu-central-1
  AWS_LIGHTSAIL_SERVICE_NAME: bussie-backend
  AWS_LIGHTSAIL_SCRAPER_NAME: bussie-scraper
jobs:
          
  buildingimage:
    name: ğŸš€ Launching new version...
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ—‚  Getting all the code Peter has written
        uses: actions/checkout@v2
      - name: âš™ï¸  Updating to the latest versions
        run: |
          sudo apt-get update
          sudo apt-get install -y jq unzip
      - name: ğŸ¢ Install Amazon Client
        run: |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install || true
          aws --version
          curl "https://s3.us-west-2.amazonaws.com/lightsailctl/latest/linux-amd64/lightsailctl" -o "lightsailctl"
          sudo mv "lightsailctl" "/usr/local/bin/lightsailctl"
          sudo chmod +x /usr/local/bin/lightsailctl
      - name: ğŸ¤ Log in to AWS Lightsail with Secrets
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ${{ env.AWS_REGION }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: ğŸ³ Create a Docker Container for Backend
        run: docker build -t bussie-backend:latest .
      - name: ğŸ“¬ Upload Backend image to AWS container register
        run: |
          service_name=${{ env.AWS_LIGHTSAIL_SERVICE_NAME }}
          aws lightsail push-container-image \
            --region ${{ env.AWS_REGION }} \
            --service-name ${service_name} \
            --label ${service_name} \
            --image ${service_name}:latest
      - name: ğŸ³ Create a Docker Container for Scraper
        run: cd bussie_backend/data_collection
      - name: ğŸ³ CHange folder
        run: docker build -t bussie-scraper:latest .
      - name: ğŸ“¬ Upload Scraper image to AWS container register
        run: |
          service_name1=${{ env.AWS_LIGHTSAIL_SCRAPER_NAME }}
          aws lightsail push-container-image \
            --region ${{ env.AWS_REGION }} \
            --service-name ${service_name1} \
            --label ${service_name1} \
            --image ${service_name1}:latest
      - run: cd ../..
      - run: pwd
      - name: ğŸš€ Deploying the container to the Amazon datacenter
        run: |
          aws lightsail create-container-service-deployment --service-name bussie-backend \
            --containers file://Infrastructure/deploymentconfig.json \
            --public-endpoint file://Infrastructure/publicendpoint.json
      - name: =========== All done. Cleaning up â™»ï¸  ===========
        run: ls